MacOS Port
datasnakes/renv pull request #60
Opened 2019-10-19 23:51 UTC by r614

MacOS implementation for renv. 
Mentioned in #59

2019-10-20 17:11 UTC, sdhutchins commented
Hey, @r614 ! The issue with Travis CI is with the python versions. 

In the [pyproject.toml](https://github.com/datasnakes/renv/blob/master/pyproject.toml), the python version should be bumped up to `3.5`.

```yaml
[tool.poetry.dependencies]
python = ">=3.4"
click = "^7.0"
pyyaml = "^3.12"
cookiecutter = "^1.6"
```

For the [travis.yml](https://github.com/datasnakes/renv/blob/master/.travis.yml) file, python version 3.4 should be removed.

```yaml
python:
  - 3.4
  - 3.5
  - 3.6
 ```

2019-10-20 17:15 UTC, r614 commented
Hey @sdhutchins , just fixed it!

2019-10-20 17:16 UTC, grabear commented
Ohh!  It's building :)

2019-10-20 17:52 UTC, sdhutchins commented
Nice job, @r614 !!!

2019-10-20 17:53 UTC, grabear commented on poetry.lock
> +version = "0.13.2"
```suggestion
version = "0.14.0"
```

2019-10-20 18:11 UTC, grabear commented
Bump the project version in the poetry.toml file from `0.3.1` to `0.4.0`

2019-10-20 18:14 UTC, grabear requested changes
Bump the project version in the poetry.toml file from `0.3.1` to `0.4.0`

2019-10-21 18:25 UTC, r614 commented
Updated!

2019-10-24 15:18 UTC, grabear approved these changes

2019-10-24 15:18 UTC, merged

2019-10-24 15:18 UTC, grabear commented
Nice job @r614 :)

2019-10-24 19:09 UTC, r614 commented
Thanks. :D